# Cloud Build configuration for Python Flask social media scheduler
steps:
  # Step 1: Build Docker image using Cloud Native Buildpacks
  - name: 'gcr.io/k8s-skaffold/pack'
    entrypoint: 'pack'
    args: [
      'build',
      'gcr.io/$PROJECT_ID/social-media-scheduler:$BUILD_ID',
      '--builder=gcr.io/buildpacks/builder:v1',
      '--publish'
    ]
    
  # Step 2: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'social-media-scheduler',
      '--image', 'gcr.io/$PROJECT_ID/social-media-scheduler:$BUILD_ID',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '1Gi',
      '--cpu', '1',
      '--timeout', '3600',
      '--max-instances', '10',
      '--set-env-vars', 'PORT=8080'
    ]

# Store images in Container Registry  
images:
  - 'gcr.io/$PROJECT_ID/social-media-scheduler:$BUILD_ID'

# Timeout for the entire build
timeout: '1200s'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
