# Cloud Build configuration for social media scheduler
steps:
  # Step 1: Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']

  # Step 2: Run tests (optional)
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['test']
    env:
      - 'CI=true'

  # Step 3: Build the application
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Step 4: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/social-media-scheduler:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/social-media-scheduler:latest',
      '.'
    ]

  # Step 5: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'gcr.io/$PROJECT_ID/social-media-scheduler:$BUILD_ID'
    ]

  # Step 6: Deploy to Cloud Run (optional)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'social-media-scheduler',
      '--image', 'gcr.io/$PROJECT_ID/social-media-scheduler:$BUILD_ID',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/social-media-scheduler:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/social-media-scheduler:latest'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_STANDARD_2'

# Timeout for the entire build
timeout: '1200s'
