cat > cloudbuild.yaml << 'EOF'
# Cloud Build configuration for Python Flask social media scheduler
steps:
  # Step 1: Install Python dependencies
  - name: 'python:3.9-slim'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt']

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/social-media-scheduler:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/social-media-scheduler:latest',
      '.'
    ]

  # Step 3: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'gcr.io/$PROJECT_ID/social-media-scheduler:$BUILD_ID'
    ]

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'social-media-scheduler',
      '--image', 'gcr.io/$PROJECT_ID/social-media-scheduler:$BUILD_ID',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '512Mi',
      '--timeout', '300'
    ]

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/social-media-scheduler:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/social-media-scheduler:latest'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY

# Timeout for the entire build
timeout: '1200s'
EOF
